pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                echo 'Deploying Changes to Web Server...'
                ls
                cp -a web-app/* /var/www/html/
                sudo service nginx restart
            }
        }
    }
}
