pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                echo 'Deploying Changes to Web Server...'
                ls
                sh 'cp -a web-app/* /var/www/html/'
                sh 'sudo service nginx restart'
            }
        }
    }
}
