pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                echo 'Deploying Changes to Web Server...'
                sh 'ls' // Verify files in dir
                sh 'sudo cp -a web-app/* /var/www/html/'
                sh 'sudo service nginx restart'
            }
        }
    }
}
